spring:
  application:
    name: myFirstProject

  data:
    mongodb:
      uri: mongodb+srv://sarthakbobhate:Sarthak4207@cluster0.hz9ezxb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  port: 8090
  servlet:
    context-path: /journal

weather:
  api:
    key: 2da240b29b6e80310154e5350b40246f

#weather_api_key: 2da240b29b6e80310154e5350b40246f